services:
  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: pipeline
      POSTGRES_PASSWORD: pipeline
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./sql/analytics:/analytics
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pipeline -d payments"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
